---
title: "stl_lead_inequity"
author: "Jake Eisaguirre"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(skimr)
```

#read in data and explore
```{r}
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"))

skimr::skim(stl_lead)
summary(stl_lead)


```

#clean data
```{r}

stl_lead <- janitor::clean_names(stl_lead)
stl_lead

```
# new data frame and columnn
```{r}

stl_lead_prop <- stl_lead %>% 
  mutate(prop_white = (white / total_pop)*100) %>% 
  mutate(pct_elevated = str_replace(pct_elevated, patter = ",",
                                                  replacement = ".")) %>% 
  mutate(pct_elevated = as.numeric(pct_elevated))



```

#create scatter plot
```{r width = 5 height =12}

stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) + 
  geom_point(aes(), color = 'red', size = 3, alpha = 1/3, fig.dim = c(4,6)) 


stl_lead_plot

```
## there seems to be a negative correlation between pct_elevated and prop_white


# save plot
```{r}
ggsave(here::here("fig", "stl_lead_plot.png"), height = 6, width = 5)
```

#create histo
```{r}
ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(color = 'blue', binwidth = 2, fill = "pink")


```
# now save it
```{r}
ggsave(here::here("fig", "pct_elevated.jpg"))
```

